name: Go pipeline

on:
  push:
    # all branches
  pull_request:
    # all branches

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'

      - name: Install dependencies
        run: go mod tidy

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: go test -v ./...

  build-and-zip:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build and zip executable
        run: make build-and-zip
