name: Go pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'
      - name: Install dependencies
        run: go mod tidy
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Build and zip executable
        run: make build-and-zip
      - name: Push zip
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name ${{ secrets.AWS_LAMBDA_ARN }} \
            --zip-file fileb://bin/bootstrap.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"